# Generated by Django 4.1.1 on 2022-09-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Travel_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("mesto", models.IntegerField()),
                ("price_one_mesto", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("rastoyanie", models.CharField(max_length=100000)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "regions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rockay.travel_type",
                        verbose_name="region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("rastoyanie", models.CharField(max_length=100000)),
                ("picture", models.ImageField(upload_to="static/")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "regions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rockay.region",
                        verbose_name="region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Living",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("adress", models.CharField(max_length=60)),
                ("card", models.ImageField(upload_to="static/")),
                ("geo_location", models.IntegerField()),
                ("price", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rockay.location",
                        verbose_name="region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kitchen", models.IntegerField()),
                ("description", models.CharField(max_length=100000)),
                ("price_one_day", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "regions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rockay.location",
                        verbose_name="region",
                    ),
                ),
            ],
        ),
    ]
