# Generated by Django 4.1.1 on 2022-09-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="description",
        ),
        migrations.AddField(
            model_name="food",
            name="opisanie",
            field=models.CharField(default="kl", max_length=1000),
            preserve_default=False,
        ),
    ]
