# Generated by Django 4.1.1 on 2022-09-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0002_remove_food_description_food_opisanie"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="svyzb",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rockay.location",
                verbose_name="region",
            ),
            preserve_default=False,
        ),
    ]
