# Generated by Django 4.1.1 on 2022-09-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0003_route_svyzb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="svyzb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rockay.location",
                verbose_name="boo",
            ),
        ),
    ]
