# Generated by Django 4.1.1 on 2022-09-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0004_alter_route_svyzb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="kitchen",
            field=models.CharField(max_length=500),
        ),
    ]
