# Generated by Django 4.1.1 on 2022-09-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0005_alter_food_kitchen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="svyzb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rockay.location",
                verbose_name="bose",
            ),
        ),
    ]
