# Generated by Django 4.1.1 on 2022-09-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0006_alter_route_svyzb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="regions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rockay.travel_type",
                verbose_name="traveltype",
            ),
        ),
    ]
