# Generated by Django 4.1.1 on 2022-09-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rockay", "0007_alter_route_regions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="regions",
            new_name="travel_type",
        ),
        migrations.AlterField(
            model_name="route",
            name="svyzb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rockay.location",
                verbose_name="travelvid",
            ),
        ),
    ]
